# Generated by Django 5.2.8 on 2025-11-10 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(help_text='Email du client', max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.CharField(editable=False, help_text='Numéro de compte unique', max_length=20, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='banking.client')),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('DEP', 'Dépôt'), ('RET', 'Retrait')], max_length=3)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='banking.comptebancaire')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date_heure'],
            },
        ),
    ]
