# Generated by Django 5.2.8 on 2025-11-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_client_email_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comptebancaire',
            options={},
        ),
        migrations.AddField(
            model_name='operation',
            name='date_validation',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='source',
            field=models.CharField(blank=True, choices=[('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('NON', 'N/A')], default='NON', max_length=3),
        ),
        migrations.AddField(
            model_name='operation',
            name='statut',
            field=models.CharField(choices=[('ATT', 'En attente'), ('VAL', 'Validée'), ('ANN', 'Annulée')], default='ATT', max_length=3),
        ),
    ]
