# Generated by Django 5.2.8 on 2025-11-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_client_options_alter_comptebancaire_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='comptebancaire',
            options={'verbose_name': 'Compte Bancaire', 'verbose_name_plural': 'Comptes Bancaires'},
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
