# Generated by Django 5.2.8 on 2025-11-17 05:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_client_options_alter_comptebancaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
