# Generated by Django 5.2.8 on 2025-11-17 06:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_operation_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptebancaire',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
